[workspace]
members = ["infur", "ff-video", "image-ext"]

[profile.dev.package]
image-ext = { opt-level = 3 }
tract-core = { opt-level = 3 }
tract-onnx = { opt-level = 3 }
tract-onnx-opl = { opt-level = 3 }
