[package]
name = "ff-video"
description = "Slim image decoding with ffmpeg."
version.workspace = true
edition.workspace = true

[dependencies]
image-ext = { path = "../image-ext" }
thiserror.workspace = true
tracing.workspace = true
