[package]
name = "ff-video"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image-ext = { path = "../image-ext" }
thiserror = "1"
tracing = "0.1"
