[package]
name = "infur"
version = "0.1.0"
edition = "2021"
description = "show case onnx model inference on video stream"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tracing-subscriber = "0.3"
tract-onnx = "0.17"
image-ext = { path = "../image-ext" }
ff-video = { path = "../ff-video" }
