name: test

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install pre-commit
        run:
          pip install pre-commit
          pre-commit install
      - run: pre-commit run --all-files --show-diff-on-failure
        env:
          INFUR_NO_TEST_GEN: 1
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup-ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      - run: cargo version -v
      - run: ffmpeg -version
      - uses: actions/checkout@v3
      - run: cargo test
